apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: monitoring
data:
  prometheus-rules.yml: |
    groups:
      - name: kubernetes-pod-rules
        rules:
          - alert: PodCrashLoopBackOff
            expr: count_over_time(kube_pod_container_status_waiting_reason{reason="CrashLoopBackOff"}[5m]) > 1
            for: 1m
            labels:
              severity: critical
            annotations:
              description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is in CrashLoopBackOff."
              summary: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} has exceeded the threshold for CrashLoopBackOff."
