apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    alerting:
      alertmanagers:
        - static_configs:
            - targets:
                - '10.43.181.40:9093'
    rule_files:
      - '/etc/prometheus/prometheus-rules.yml'
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['10.43.51.200:8080']
      - job_name: 'cadvisor'
        static_configs:
          - targets: ['10.43.146.191:8085']
      - job_name: 'alertmanager'
        static_configs:
          - targets: ['10.43.181.40:9093']
